In [37]:
import boto3
import pandas
import numpy as np

In [38]:
pop = pandas.read_csv('population_by_country_2020.csv')
df = pandas.read_csv('OECD_WATER_ABSTRACT.csv')

In [55]:
pop.iloc[0].Population

1440297825

In [57]:
population = []
for index, row in df.iterrows():
    popNo = pop[pop["Country"] == row["Country"]]['Population']
    print(popNo)
    population.append(popNo)
    
df['population'] = population
df.to_csv(index=False, path_or_buf='final_water_population.csv')

54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
54    25550683
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
96    9015361
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64
80    11598451
Name: Population, dtype: int64